Update CI scripts

diff --git a/build b/build
--- a/build
+++ b/build
@@ -15,7 +15,6 @@ OS=unix
 BINEXT=
 ARTEFACT_OS=linux
 ARTEFACT_EXT=.tar.gz
-ARCH=x64
 if [[ "$OSTYPE" == "cygwin" || "$OSTYPE" == "msys" ]]; then
     OS=windows
     BINEXT=.exe
@@ -26,6 +25,8 @@ elif [[ -f "/etc/alpine-release" ]]; then
 fi
 
 COMPONENT="libsawyer"
+CONFIGURATION=Release
+PLATFORM=x64
 while (( "$#" )); do
     case "$1" in
         --static)
@@ -35,6 +36,15 @@ while (( "$#" )); do
         -c)
             if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
                 CONFIGURATION=$2
+                shift 2
+            else
+                echo "Error: Argument for $1 is missing" >&2
+                exit 1
+            fi
+            ;;
+        -p)
+            if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
+                PLATFORM=$2
                 shift 2
             else
                 echo "Error: Argument for $1 is missing" >&2
@@ -55,14 +65,10 @@ while (( "$#" )); do
     esac
 done
 
-if [ "$CONFIGURATION" = "" ]; then
-    CONFIGURATION=Release
-fi
-
 VCPKG_TRIPLET_ARG=""
 VCPKG_TOOLCHAIN_ARG=""
 if [ "$STATIC" == "true" ]; then
-    VCPKG_TRIPLET_ARG="-DVCPKG_TARGET_TRIPLET=x64-windows-static"
+    VCPKG_TRIPLET_ARG="-DVCPKG_TARGET_TRIPLET=$PLATFORM-windows-static"
     STATIC_DESC="-static"
 fi
 if [ "$OS" == "windows" ]; then
@@ -101,7 +107,7 @@ if [[ "$COMPONENT" = "libsawyer" ]]; then
     $CMAKE_CONFIGURE_CMD
     $CMAKE_BUILD_CMD
     $CMAKE_INSTALL_CMD
-    archive "libsawyer-$ARTEFACT_OS-$ARCH$STATIC_DESC$ARTEFACT_EXT" out
+    archive "libsawyer-$ARTEFACT_OS-$PLATFORM$STATIC_DESC$ARTEFACT_EXT" out
 fi
 
 if [[ "$COMPONENT" = "fsaw" ]]; then
@@ -126,6 +132,6 @@ if [[ "$COMPONENT" = "tools" ]]; then
     mkdir -p temp
     cp "tools/fsaw/bin/fsaw$BINEXT" temp
     cp "tools/spritec/bin/spritec$BINEXT" temp
-    archive "libsawyer-tools-$ARTEFACT_OS-$ARCH$ARTEFACT_EXT" temp
+    archive "libsawyer-tools-$ARTEFACT_OS-$PLATFORM$ARTEFACT_EXT" temp
     rm -rf temp
 fi
